services:
  api:
    container_name: rust-api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:3000"
  frontend:
    container_name: smart-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    ports:
      - "3000:80"
