apiVersion: v1
kind: Service
metadata:
  name: rust-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app: rust-api
    version: {{ .Values.rustApi.version }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.rustApi.port }}
      targetPort: {{ .Values.rustApi.port }}
      protocol: TCP
  selector:
    app: rust-api
    version: {{ .Values.rustApi.version }}
