apiVersion: v1
kind: Service
metadata:
  name: mypostgres-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mypostgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
